spring:
  data:
    rest:
      base-path: /api
  datasource:
    url: jdbc:mysql://localhost:3306/lottery
    username: root
    password: root
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
